#docker compose with load balancing

services:
  web1:
    build: .
    ports:
      - "5000:5000"
    healthcheck:
      test: curl --fail http://localhost:5000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - webnet
  web2:
    build: .
    ports:
      - "5001:5000"
    healthcheck:  
      test: curl --fail http://localhost:5000 || exit 1 
      interval: 30s      
      timeout: 10s      
      retries: 5      
      start_period: 30s
    networks:
      - webnet
  web3:
    build: .
    ports:
      - "5002:5000"
    healthcheck:  
      test: curl --fail http://localhost:5000 || exit 1 
      interval: 30s      
      timeout: 10s      
      retries: 5      
      start_period: 30s
    networks:
      - webnet
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-logs.conf:/etc/logrotate.d/nginx
      - "/var/log/nginx:/var/log/nginx"
    networks:
      - webnet
    depends_on:
      - web1
      - web2
      - web3
networks:
  webnet: 
    driver: bridge
